import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslocoModule } from '@jsverse/transloco';
import { PipeModule } from '../pipe/pipe.module';
import {
  IonRouterOutlet,
  IonApp,
  IonHeader,
  IonContent,
  IonInput,
  IonAvatar,
  IonList,
  IonItem,
  IonInputPasswordToggle,
  IonButton,
  IonItemDivider,
  IonLabel,
  IonCheckbox,
  IonIcon,
  IonNav,
  IonNavLink,
  IonToolbar,
  IonButtons,
  IonTitle,
  IonBackButton,
  IonSkeletonText,
  IonModal,
  IonCard,
  IonCardHeader,
  IonCardContent,
  IonCardTitle,
  IonCardSubtitle,
  IonInfiniteScroll,
  IonInfiniteScrollContent,
} from "@ionic/angular/standalone";
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    RouterModule,
    ReactiveFormsModule,
    FormsModule,
    TranslocoModule,
    PipeModule,
    IonApp,
    IonHeader,
    IonRouterOutlet,
    IonContent,
    IonInput,
    IonAvatar,
    IonList,
    IonItem,
    IonInputPasswordToggle,
    IonButton,
    IonItemDivider,
    IonLabel,
    IonCheckbox,
    IonIcon,
    IonNav,
    IonNavLink,
    IonToolbar,
    IonButtons,
    IonTitle,
    IonBackButton,
    IonSkeletonText,
    IonModal,
    IonCard,
    IonCardHeader,
    IonCardContent,
    IonCardTitle,
    IonCardSubtitle,
    IonInfiniteScroll,
    IonInfiniteScrollContent,
  ],
  exports: [
    RouterModule,
    ReactiveFormsModule,
    FormsModule,
    TranslocoModule,
    PipeModule,
    IonApp,
    IonHeader,
    IonRouterOutlet,
    IonContent,
    IonInput,
    IonAvatar,
    IonList,
    IonItem,
    IonInputPasswordToggle,
    IonButton,
    IonItemDivider,
    IonLabel,
    IonCheckbox,
    IonIcon,
    IonNav,
    IonNavLink,
    IonToolbar,
    IonButtons,
    IonTitle,
    IonBackButton,
    IonSkeletonText,
    IonModal,
    IonCard,
    IonCardHeader,
    IonCardContent,
    IonCardTitle,
    IonCardSubtitle,
    IonInfiniteScroll,
    IonInfiniteScrollContent,
  ]
})
export class ShareModule { }
